# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gps_agent_pkg/ControllerParams.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gps_agent_pkg.msg

class ControllerParams(genpy.Message):
  _md5sum = "b21eed6449b84a548fab33a89f3b3c3b"
  _type = "gps_agent_pkg/ControllerParams"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 controller_to_execute  # controller enum, defined in gps_pb2

CaffeParams caffe
LinGaussParams lingauss
TfParams tf

================================================================================
MSG: gps_agent_pkg/CaffeParams
string net_param # Serialized net parameter with weights (equivalent of prototxt file)
float32[] bias
float32[] scale
float32[] noise
int32 dim_bias
uint32 dU

================================================================================
MSG: gps_agent_pkg/LinGaussParams
# Time-varying Linear Gaussian controller
uint32 dX
uint32 dU
float64[] K_t  # Should be T x Du x Dx
float64[] k_t  # Should by T x Du

================================================================================
MSG: gps_agent_pkg/TfParams
# Tf Params. just need to track dU.
uint32 dU

"""
  __slots__ = ['controller_to_execute','caffe','lingauss','tf']
  _slot_types = ['int8','gps_agent_pkg/CaffeParams','gps_agent_pkg/LinGaussParams','gps_agent_pkg/TfParams']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       controller_to_execute,caffe,lingauss,tf

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControllerParams, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.controller_to_execute is None:
        self.controller_to_execute = 0
      if self.caffe is None:
        self.caffe = gps_agent_pkg.msg.CaffeParams()
      if self.lingauss is None:
        self.lingauss = gps_agent_pkg.msg.LinGaussParams()
      if self.tf is None:
        self.tf = gps_agent_pkg.msg.TfParams()
    else:
      self.controller_to_execute = 0
      self.caffe = gps_agent_pkg.msg.CaffeParams()
      self.lingauss = gps_agent_pkg.msg.LinGaussParams()
      self.tf = gps_agent_pkg.msg.TfParams()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.controller_to_execute
      buff.write(_get_struct_b().pack(_x))
      _x = self.caffe.net_param
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.caffe.bias)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.caffe.bias))
      length = len(self.caffe.scale)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.caffe.scale))
      length = len(self.caffe.noise)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.caffe.noise))
      _x = self
      buff.write(_get_struct_i3I().pack(_x.caffe.dim_bias, _x.caffe.dU, _x.lingauss.dX, _x.lingauss.dU))
      length = len(self.lingauss.K_t)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.lingauss.K_t))
      length = len(self.lingauss.k_t)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.lingauss.k_t))
      _x = self.tf.dU
      buff.write(_get_struct_I().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.caffe is None:
        self.caffe = gps_agent_pkg.msg.CaffeParams()
      if self.lingauss is None:
        self.lingauss = gps_agent_pkg.msg.LinGaussParams()
      if self.tf is None:
        self.tf = gps_agent_pkg.msg.TfParams()
      end = 0
      start = end
      end += 1
      (self.controller_to_execute,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.caffe.net_param = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.caffe.net_param = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.caffe.bias = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.caffe.scale = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.caffe.noise = s.unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.caffe.dim_bias, _x.caffe.dU, _x.lingauss.dX, _x.lingauss.dU,) = _get_struct_i3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lingauss.K_t = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lingauss.k_t = s.unpack(str[start:end])
      start = end
      end += 4
      (self.tf.dU,) = _get_struct_I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.controller_to_execute
      buff.write(_get_struct_b().pack(_x))
      _x = self.caffe.net_param
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.caffe.bias)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.caffe.bias.tostring())
      length = len(self.caffe.scale)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.caffe.scale.tostring())
      length = len(self.caffe.noise)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.caffe.noise.tostring())
      _x = self
      buff.write(_get_struct_i3I().pack(_x.caffe.dim_bias, _x.caffe.dU, _x.lingauss.dX, _x.lingauss.dU))
      length = len(self.lingauss.K_t)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.lingauss.K_t.tostring())
      length = len(self.lingauss.k_t)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.lingauss.k_t.tostring())
      _x = self.tf.dU
      buff.write(_get_struct_I().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.caffe is None:
        self.caffe = gps_agent_pkg.msg.CaffeParams()
      if self.lingauss is None:
        self.lingauss = gps_agent_pkg.msg.LinGaussParams()
      if self.tf is None:
        self.tf = gps_agent_pkg.msg.TfParams()
      end = 0
      start = end
      end += 1
      (self.controller_to_execute,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.caffe.net_param = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.caffe.net_param = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.caffe.bias = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.caffe.scale = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.caffe.noise = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 16
      (_x.caffe.dim_bias, _x.caffe.dU, _x.lingauss.dX, _x.lingauss.dU,) = _get_struct_i3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lingauss.K_t = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lingauss.k_t = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (self.tf.dU,) = _get_struct_I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
_struct_i3I = None
def _get_struct_i3I():
    global _struct_i3I
    if _struct_i3I is None:
        _struct_i3I = struct.Struct("<i3I")
    return _struct_i3I
